# AUTOGENERATED! DO NOT EDIT! File to edit: 01_core_utility.ipynb (unless otherwise specified).

__all__ = ['LhtFile', 'FindFilesByExtension']

# Cell
import os

# Cell
class LhtFile:
    '''
    Self-defined class, which is used to record the file name and file path.
    '''
    def __init__(self,fileName, filePath):
        self.file_name = fileName
        self.file_path = filePath


# Cell
def FindFilesByExtension(root_directory, extension):
    '''
    Filter all files based on the extention.
    Parameters:
        [in] root_directory: the path of a directory
        [in] extension: file extension
    Return:
        ret: a list made of LhtFile objects.
    '''
    ret = []
    for (root, dirs, files) in os.walk(root_directory, topdown=True):
        for f in files:
            if f.endswith(extension):
                fileName = f
                filePath = os.path.join(root,f)
                lhtJson = LhtFile(fileName,filePath)
                ret.append(lhtJson)
    return ret